services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8085:80" # To start localy
      #- "80:80"  # Deploy on the vm
    depends_on:
      - my_web_service
      - my_interface

  my_web_service:
    build: ./src
    container_name: my_web_service
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
          limits:
            memory: 10g

  my_interface:
    build: ./src/interface
    container_name: my_interface
    environment:
      - REACT_APP_MY_API_URI=http://localhost:8085

