services:
  nginx:
    image: nginx:latest
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"  # Expose sur le port 80
    depends_on:
      - my_web_service
      - my_interface

  my_web_service:
    build: ./src/my_api
    container_name: my_web_service

  my_interface:
    build: ./src/interface
    container_name: my_interface
    environment:
      - REACT_APP_MY_API_URI=http://localhost:8085

