on: [push, pull_request]

jobs:
  check-pattern:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for Pattern in Commit Message
      run: |
        if [[ ! "${{ github.event.head_commit.message }}" =~ ^(feat|fix|chore|refactor)\(.*\):\ .* ]]; then
          echo "Commit message does not match the required pattern: <type>(<scope>): <description>"
          exit 1
        fi
      shell: bash
