name: Deploy to VM

on:
  push:
    branches:
      - main
      - 22-deploy-automatically-with-ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync openssh-client sshpass iputils-ping netcat


    - name: Debug Connectivity
      run: |
        echo "Testing connectivity..."
        ping -c 4 <server-ip> || echo "Ping failed"
        nc -zv <server-ip> 22 || echo "Port 22 unreachable"

    - name: Copy Project to Server
      run: |
        sshpass -p '${{secrets.SSH_PWD}}' rsync -avz --exclude='.git' -e "ssh -vvv -o StrictHostKeyChecking=no" ./Makefile "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:./nlp-argument/"


    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd nlp-argument
          docker-compose down
          docker-compose up -d --build
        EOF
