name: CI-Workflow
on: [push, pull_request]

jobs:
  check-vm:
    runs-on: ubuntu-latest
    steps:
      - name: Check if VM is running
        id: check-vm
        run: |
          VM_IP="${{secrets.SSH_HOST}}"
          if ping -c 1 $VM_IP &> /dev/null; then
            echo "VM is running."
            echo "::set-output name=vm_running::true"
          else
            echo "VM is not running. Aborting CI."
            echo "::set-output name=vm_running::false"
            exit 0
          fi
  deploy:
    runs-on: ubuntu-latest
    if: needs.check-vm.outputs.vm_running == 'true'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync openssh-client sshpass iputils-ping netcat

    - name: Copy Project to Server
      run: |
        sshpass -p '${{secrets.SSH_PWD}}' rsync -avz --exclude='.git' -e "ssh -vvv -o StrictHostKeyChecking=no" ./ "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:./nlp-argument"

    - name: Deploy with Docker Compose
      run: |
        sshpass -p '${{secrets.SSH_PWD}}' ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd nlp-argument
          docker-compose down
          docker-compose up -d --build
        EOF
