name: Deploy to VM

on:
  push:
    branches:
      - main
      - 22-deploy-automatically-with-ci

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install rsync
      run: |
        sudo apt-get update
        sudo apt-get install -y rsync openssh-client sshpass
    - name: Debug
      run: |
        echo "Testing IPv6 connectivity..."
        ping6 -c 4 2a01:cb00:dd6:dd00:a00:27ff:fe1c:a3d3 || echo "Ping failed"
        echo "Testing SSH port availability..."
        nc -zv -6 2a01:cb00:dd6:dd00:a00:27ff:fe1c:a3d3 22 || echo "Port 22 unreachable"

    - name: Copy Project to Server
      run: |
        sshpass -p 'toto1234' rsync -avz --exclude='.git' -e "ssh -6 -v -o StrictHostKeyChecking=no" ./ "toto@[2a01:cb00:dd6:dd00:a00:27ff:fe1c:a3d3]:./nlp-argument/"


    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          cd nlp-argument
          docker-compose down
          docker-compose up -d --build
        EOF
