name: CI-Workflow
on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: checkout source repo
      uses: actions/checkout@2

    - name: linting
      uses: programmingwithalex/pylinter@main
      with:
        python-root: './src'
        flake8-flags: ''
        mypy-flags: ''
        fail-on-isort: false
        # skip-flake8: false
        # skip-mypy: false
        # skip-isort: false
        # mypy-ignore-dirs-files: ''
        # requirements-file: ''

    - name: commit isort changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'refacto(isort): apply isort to code'

    - name: push isort changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
